### ISSUE TITLE
Fix last row labelling error

### ISSUE THREAD

**Issue by Patrick-Ivann** [juliengriffoul/labelx#3]
Error Pops out on the element to label while reading a CSV

index, current_row = get_first_non_labelled_row(

**Comment by Patrick-Ivann** [comment]
Traceback (most recent call last):
  File "/Users/ivannorigo/Documents/Datascience/labelexreact/labelx/env/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ivannorigo/Documents/Datascience/labelexreact/labelx/env/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/ivannorigo/Documents/Datascience/labelexreact/labelx/env/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ivannorigo/Documents/Datascience/labelexreact/labelx/env/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ivannorigo/Documents/Datascience/labelexreact/labelx/env/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ivannorigo/Documents/Datascience/labelexreact/labelx/env/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/ivannorigo/Documents/Datascience/labelexreact/labelx/labelx/main.py", line 55, in index
    index, current_row = get_first_non_labelled_row(
  File "/Users/ivannorigo/Documents/Datascience/labelexreact/labelx/labelx/file.py", line 62, in get_first_non_labelled_row
    return index, current_row
UnboundLocalError: local variable 'current_row' referenced before assignment

**Comment by Patrick-Ivann** [comment]
Steps to reproduce: 

Load up a +800 lines csv files
configure 3 fields
2 value labels
delimiter ";"

issue pops up after labelling the last row
